### ISSUE TITLE
Do we need the null default?

### ISSUE THREAD

**Issue by bwoebi** [async-interop/promise#1]
> Calling this method without a callback will throw the exception from a failed awaitable in an uncatchable way.

To be honest, something like `$promise->when();` looks off and buggy to me. You do an action on when(), not "null". Intuitively, if this would pass, I'd accept it to do absolutely nothing (does exactly null/zero things).

**Comment by trowski** [comment]
I wasn't sure about it myself. It was meant to be a convenience way to forward exceptions to an `onError` handler in the loop. However, for a general interface it may be better to not allow null and require users to explicitly set a callback.

``` php
function (Exception $exception = null) {
    if ($exception) throw $exception;
}
```

**Comment by trowski** [comment]
@bwoebi @kelunik Closing per our discussion in chat and #3.
