### ISSUE TITLE
Typehint resolved / rejected value

### ISSUE THREAD

**Issue by joelwurtz** [async-interop/promise#11]
Is there a way, despite documentation, to extend Awaitable in order to force a specific type of value to be returned or rejected ?

Let's imagine i have a Awaitable that will be resolved by integer and i clearly state that it will return a integer, but on the other side i allow other library to inject their own callback, is there a way to force an interface so i'm sure that the contract i have set is respected ?

**Comment by bwoebi** [comment]
I personally like Generic syntax for that `@return Awaitable<int> Resolving to the best integer value ever existing`.

But there is no enforcement possible, no.

**Comment by kelunik** [comment]
@joelwurtz You could theoretically build a custom `Awaitable` that accepts a type in form of a string in the constructor and checks upon resolution. But without generics, there's no good way to restrict things.

**Comment by joelwurtz** [comment]
Ok thanks
