### ISSUE TITLE
Working with immutable value

### ISSUE THREAD

**Issue by joelwurtz** [async-interop/promise#12]
Hey,

How do you do when you want to change a value that is immutable, and reuse use the changed value in other callback ?

I'm asking this because we work on ResponseInterface from PSR7 which are immutable, right now we use a Promise, but we would love to use async-interop in the near futur (once it's close to be stable).

But depending on Awaitable seems to be hard to do for immutable data as we would have to do the following: 

``` php
$tempResponse = null;

$awaitable->when(function($error, $response) use (&$tempResponse ) {
    $tempResponse = $response->withHeader();
}); 

$awaitable->when(function($error, $response) use (&$tempResponse) {
    $tempResponse = $tempResponse->withBody();
});
```

And this get even weird when the `when` method is called somewhere else as we would have to transfer the reference to $tempResponse.

Or is there a better way ?

**Comment by joelwurtz** [comment]
Okay nevermind we should just do the following: 

``` php
$awaitable->when(function($error, &$response) {
    $response = $response->withHeader();
});
```

But is it valid for the spec ?

**Comment by bwoebi** [comment]
The spec doesn't specify what happens then. It's undefined behavior. The spec mandates the passed callbacks to not include by-ref parameters. If they do, that's the callers fault.

**Comment by kelunik** [comment]
Don't do that. Resolved values MUST NOT change, that's what the spec says.

You better just use coroutines and it will work like in a synchronious world.

**Comment by joelwurtz** [comment]
So the following ?:

``` php
$awaitable->when(function($error, $response) {
    yield $response->withHeader();
});
```

**Comment by bwoebi** [comment]
Nah.

You need to create a new Awaitable. Check the library you use for Awaitable creation.

A library like Amp has a function `pipe()` which transforms the Awaitable and returns a new one:

```
$awaitable = \Amp\pipe($awaitable, function($response) { return $response->withHeader(); });
$awaitable->when(function($error, $response) { ... });
```

This pipe function then looks like (pseudo-code):

```
function pipe($awaitable, $callback) {
    // the Future can be resolved or failed and may be asked for the related Awaitable
    $future = new Future;
    $awaitable->when(function($error, $result) use ($callback, $future) {
         if (!$error) {
             $future->resolve($callback($result));
         } else {
             $future->fail($error);
         }
    });
    return $future->getAwaitable();
}
```

You definitely ought to _not_ change the value of an Awaitable directly. The Awaitable should always call the callbacks passed to when() with the same `$error, $result` pair.

**Comment by joelwurtz** [comment]
> Check the library you use for Awaitable creation.

That's the point we don't want to be link to any library implementing "Awaitable" as we want the user using our lib to choose his own implementation.

So i will have to implement this in a generic way :/

For reference i'm speaking about this interface : https://github.com/php-http/httplug/blob/master/src/HttpAsyncClient.php and we are using a huge number of decorator to handle various thing.

**Comment by bwoebi** [comment]
The standard is really just ensuring pure interoperability. It does - intentionally - not provide functions for Awaitable _manipulation_. That's the task of the libraries.

The user of your lib will still be able to choose his own implementation. You can use some library and at the boundaries of your library, all you are communicating is Awaitables. Awaitables from one library can absolutely just used by every other library  the user wishes to use. Just because your library is based on e.g. Amp, that doesn't mean that an user cannot use it in a React context - after all, that's the whole point of interop.

**Comment by joelwurtz** [comment]
Thanks for the answer, the `pipe` thing should be documented IMO (or referenced like you did), as many people rely on this (as they have often the chainable promise in their mind when working with async)
