### ISSUE TITLE
Tag a first release

### ISSUE THREAD

**Issue by ghost** [async-interop/promise#13]
Hi everybody, will you tag a release (maybe 0.1.0) of this package anytime soon?

I am the author of [koolkode/async](https://github.com/koolkode/async), a package that provides and uses a number of classes implementing the Awaitable interface.

**Comment by kelunik** [comment]
Thanks for the reminder, I just tagged a first draft, see https://github.com/async-interop/awaitable/releases/tag/v0.1.0.
