### ISSUE TITLE
Data parameter

### ISSUE THREAD

**Issue by kelunik** [async-interop/promise#14]
In `async-interop/event-loop` we have `$data` parameters everywhere. Should we add a data parameter here as well, so the signature is `when(callable $callback, mixed $data = null)` then?

**Comment by bwoebi** [comment]
I was sure we already discussed that, but I couldn't find it right now.

I guess I'm fine with it, though it's probably unneeded and just overhead - after all, Closure binding is enough in 99.9% of cases where it isn't anyway just `yield`ed in a coroutine.
