### ISSUE TITLE
Responsibilities mixup when resolving with Awaitable

### ISSUE THREAD

**Issue by bwoebi** [async-interop/promise#16]
> If an Awaitable is resolved with another Awaitable, the Awaitable MUST keep in pending state until the passed Awaitable is resolved. Thus, the value of an Awaitable can never be an Awaitable.

Yes, the value of an Awaitable _MUST NOT_ be an Awaitable.

But an implementation might choose to e.g. not accept resolutions with Awaitables or similar. This is not our responsibility, but the responsibility of the implementing library to have sane handling for that.

Thus I propose this rewording:

> An Awaitable result MUST NOT be an Awaitable.

That's it. Awaitable resolvers can do what they want here. As long as no Awaitable is passed as result.

**Comment by kelunik** [comment]
Better simply:

> A result MUST NOT be an instance of `Awaitable`.

**Comment by kelunik** [comment]
@bwoebi I still feel that such a hint can be useful for implementers.

**Comment by bwoebi** [comment]
A hint is fine, but it should be written in the meta document rather than the specification itself.

**Comment by kelunik** [comment]
@bwoebi Could you provide a PR?
