### ISSUE TITLE
Error handler might still bubble up

### ISSUE THREAD

**Issue by kelunik** [async-interop/promise#42]
Exceptions forwarded to `ErrorHandler` might still bubble up if an error handler is set with `set_error_handler` and that one throws. Is there any reasonable way to prevent that except for calling `exit;` directly?

**Comment by bwoebi** [comment]
_If_ there is an error happening. Well, if someone is writing code which emits errors …

**Comment by kelunik** [comment]
@bwoebi What's your point?

**Comment by trowski** [comment]
Just to be clear, you're suggesting that error handlers such as the one below will still cause errors to bubble up from promise callbacks.

```php
set_error_handler(function ($errno, $errstr) {
    throw new \ErrorException($errstr, 0, $errno);
});
```

I don't think theres any way to prevent this other than calling `exit`. I looked at various solutions including setting a different error handler, but nothing made sense or just ended up going in circles.

It might be best to just wrap the [current try/catch block](https://github.com/async-interop/promise/blob/master/src/Promise/ErrorHandler.php#L79-L96) with the following:

```php
try {
    // Current try/catch block invoking error handler.
} catch (\Throwable $exception) {
    // Should we write to STDERR or just exit?
    if (\is_resource(STDERR)) { // STDERR could have been closed, so to avoid more error madness...
        \fwrite(STDERR, "It's not nice to throw things!\n");
    }
    exit(1);
} catch (\Exception $exception) {
    // Since we're still PHP 5.x compatible.
    if (\is_resource(STDERR)) {
        \fwrite(STDERR, "It's not nice to throw things!\n");
    }
    exit(1);
}
```

**Comment by kelunik** [comment]
Bluebird does in fact just the same, I'm just not sure about the exit code. https://github.com/petkaantonov/bluebird/blob/master/src/async.js#L49-L57

**Comment by kelunik** [comment]
We should probably just use `255`, just as `php -r 'throw new Exception;'; echo $?` does.

**Comment by WyriHaximus** [comment]
While I'm still strongly against using an exit in our error handlers, #43 solves it decently assuming the behavior will also be documented in the readme that implementers should avoid this edge case at all cost :+1:

**Comment by kelunik** [comment]
@WyriHaximus I've added a section to the README in the PR.

I don't see a way to avoid `exit` while at the same time guaranteeing that the exception does not bubble up to the place where `$deferred->resolve()` etc. are called.
