### ISSUE TITLE
Awaitable::when without a loop running

### ISSUE THREAD

**Issue by kelunik** [async-interop/promise#7]
We have to discuss what should happen when `Awaitable::when` is called without a Loop running and throws an exception.

**Comment by bwoebi** [comment]
I think this is a rare enough case which does not need special handling and shall just be handled normally (i.e. Loop::defer() call).
We also might declare that behavior as _undefined_ and have implementations deal with the case.

I like the option of _undefined behavior_ here as it allows libraries to invoke smarter behavior (like registering a shutdown callback to have the exception surface up in any case, if the deferred callback never gets invoked).

**Comment by kelunik** [comment]
> We also might declare that behavior as undefined and have implementations deal with the case.

No, I'd clearly define that, so `when` does never throw.

> I like the option of undefined behavior here as it allows libraries to invoke smarter behavior (like registering a shutdown callback to have the exception surface up in any case, if the deferred callback never gets invoked).

We could mention that as specifically allowed. Actually this is something an implementation could do, because it doesn't throw in `when` then, but in `register_shutdown_function`.

I actually have a use case for a `when` outside of the loop now. But it invokes `wait` later again, so the exception will appear then. If anyone is interested, I can go into more detail.

**Comment by bwoebi** [comment]
Yes, that `when()` never throws directly upon being called, should be defined.

Whether the exception will be _sometime_ thrown (i.e. when loop is discarded, script execution exited) or not, shall be implementation defined (this should be explicitly mentioned in the spec though).

Also, you're welcome to share your use case. I've not been yet able to think of a concrete one.

**Comment by kelunik** [comment]
We have an ID and fetch images. We want to fetch from two services and compare the results, because may want to switch to the other service.

``` php
$promise = $client->fetch("https://example.com/id/{$id}");
$promiseNew = $client->fetch("https://example.net/id/{$id}");

$response = wait($promise);
// send content-length header + content and flush

$responseNew = wait($promiseNew);
```

It's now easy to be in the situation that you want to log something when `$promiseNew` resolves and add something like `$promiseNew->when(...)` before `wait($promiseNew)` and `$promiseNew` might be already resolved.

Of course, you can always log it after `wait($promiseNew)`, but it's too easy to put it in front and that shouldn't matter. Using `->when` in front can have e.g. the advantage of not needing a `try` / `catch` / `finally` but executing the wanted code independently.

**Comment by bwoebi** [comment]
Closing as the PR had been merged.
