### ISSUE TITLE
Things are moving slowly

### ISSUE THREAD

**Issue by joshdifabio** [async-interop/promise#7]
Much like FIG, things seem to be moving pretty slowly here. We obviously already have lots of promise implementations out there in the wild, so we have a good idea what works and what doesn't. Is there any reason we can't start some votes and publish something?

**Comment by coderstephen** [comment]
What I *can* say, for my part at least, is that things are moving slowly not because of committee, but because not all of us have enough time to spend to keep things moving fast.

**Comment by WyriHaximus** [comment]
We have lives, work/education, and other analog world obligations. But generally when things start moving again, they flood in :smile:

**Comment by kelunik** [comment]
Also, we worked on the event loop first.

**Comment by trowski** [comment]
Without a common event loop interface, a common promise interface would be pretty useless. Once we finalize an event loop interface, some sort of promise-like interface will follow very soon afterward.

**Comment by kelunik** [comment]
@trowski You can still work on the specs in parallel.

**Comment by trowski** [comment]
@kelunik Which we are, and I guess it could be finalized first since it's a lot simpler. 😃

**Comment by WyriHaximus** [comment]
@trowski fair enough, lets get it done :smile:

**Comment by AndrewCarterUK** [comment]
With the event loop, we have the FIG structure of editors, sponsors and co-ordinators - that allows @WyriHaximus and I some authority as "editors" to lead the development drive.

As far as I am aware, there is no such structure in place for this standard. My main interest lies in the event loop, and I don't feel like I have enough experience to take a primary role in the development of a promise related standard.  I'm happy to provide input where I feel I can - but I feel someone should take responsibility for the continued development of this standard for the best results.

**Comment by joshdifabio** [comment]
There seems to have been significant progress recently. Closing this issue.
